AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Has simple function for research repository lifecycle.
Resources:
  HelloFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: handler.hello
      Runtime: python3.6
      Environment:
        Variables:
          HELLO_TABLE: !Ref HelloTable
      CodeUri: 'app.zip'
  HelloTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: Id
        Type: String
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
